// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using senai_eventPlus_webApi_codeFirst_jwt.Contexts;

#nullable disable

namespace senai_eventPlus_webApi_codeFirst_jwt.Migrations
{
    [DbContext(typeof(EventPlusContext))]
    [Migration("20231212183530_newBd")]
    partial class newBd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.Comentario", b =>
                {
                    b.Property<Guid>("idComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("exibe")
                        .HasColumnType("BIT");

                    b.Property<Guid>("idEvento")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("idComentario");

                    b.HasIndex("idEvento");

                    b.HasIndex("idUsuario");

                    b.ToTable("Comentario");

                    b.HasData(
                        new
                        {
                            idComentario = new Guid("1ca7e7e3-19f7-472f-aaf2-978ecb1dd1c6"),
                            descricao = "Excelente evento",
                            exibe = true,
                            idEvento = new Guid("5f1f1303-ca5e-49ae-9965-49b0d68d8a22"),
                            idUsuario = new Guid("620f8aa7-0f7f-4f2d-85dc-3093e7c18568")
                        });
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.Evento", b =>
                {
                    b.Property<Guid>("idEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("dataEvento")
                        .HasColumnType("DATE");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("horarioEvento")
                        .HasColumnType("TIME");

                    b.Property<Guid>("idInstituicao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idTipoEvento")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nomeEvento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)");

                    b.HasKey("idEvento");

                    b.HasIndex("idInstituicao");

                    b.HasIndex("idTipoEvento");

                    b.ToTable("Evento");

                    b.HasData(
                        new
                        {
                            idEvento = new Guid("5f1f1303-ca5e-49ae-9965-49b0d68d8a22"),
                            dataEvento = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            descricao = "Conceitos básicos do SQL Server, como DDL, DML, DQL.",
                            horarioEvento = new TimeSpan(0, 13, 0, 0, 0),
                            idInstituicao = new Guid("cd362236-3720-4143-9b41-a2ae822b625f"),
                            idTipoEvento = new Guid("798a82a9-603f-4acb-9e95-c702516521a2"),
                            nomeEvento = "Introdução ao banco de dados SQL Server"
                        });
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.Instituicao", b =>
                {
                    b.Property<Guid>("idInstituicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("VARCHAR(14)");

                    b.Property<string>("endereco")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)");

                    b.Property<string>("nomeFantasia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)");

                    b.Property<string>("razaoSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)");

                    b.HasKey("idInstituicao");

                    b.HasIndex("cnpj")
                        .IsUnique();

                    b.ToTable("Instituicao");

                    b.HasData(
                        new
                        {
                            idInstituicao = new Guid("cd362236-3720-4143-9b41-a2ae822b625f"),
                            cnpj = "1234567891012",
                            endereco = "Rua Niteroi 180",
                            nomeFantasia = "DevSchool",
                            razaoSocial = "Escola Internacional de Desenvolvimento"
                        });
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.PresencasEvento", b =>
                {
                    b.Property<Guid>("idPresencasEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idEvento")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("situacao")
                        .HasColumnType("BIT");

                    b.HasKey("idPresencasEvento");

                    b.HasIndex("idEvento");

                    b.HasIndex("idUsuario");

                    b.ToTable("PresencasEvento");

                    b.HasData(
                        new
                        {
                            idPresencasEvento = new Guid("2c7f43b4-e14d-467a-b14e-7a09e70182b8"),
                            idEvento = new Guid("5f1f1303-ca5e-49ae-9965-49b0d68d8a22"),
                            idUsuario = new Guid("620f8aa7-0f7f-4f2d-85dc-3093e7c18568"),
                            situacao = true
                        });
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.TiposEvento", b =>
                {
                    b.Property<Guid>("idTiposEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tipoEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("idTiposEvento");

                    b.HasIndex("tipoEvento")
                        .IsUnique();

                    b.ToTable("TiposEvento");

                    b.HasData(
                        new
                        {
                            idTiposEvento = new Guid("798a82a9-603f-4acb-9e95-c702516521a2"),
                            tipoEvento = "SQL Server"
                        },
                        new
                        {
                            idTiposEvento = new Guid("9b990fd5-3453-4e78-93d7-d3744e286c7a"),
                            tipoEvento = "C#"
                        });
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.TiposUsuario", b =>
                {
                    b.Property<Guid>("idTipoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tipoUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("idTipoUsuario");

                    b.HasIndex("tipoUsuario")
                        .IsUnique();

                    b.ToTable("TipoUsuario");

                    b.HasData(
                        new
                        {
                            idTipoUsuario = new Guid("f36a1eeb-7da0-4494-8d7f-75ab065b5ef9"),
                            tipoUsuario = "Administrador"
                        },
                        new
                        {
                            idTipoUsuario = new Guid("4833f49b-57d1-4c9e-a06b-6baa7bdc51d4"),
                            tipoUsuario = "Comum"
                        });
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.Usuario", b =>
                {
                    b.Property<Guid>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)");

                    b.Property<Guid>("idTipoUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("idUsuario");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("idTipoUsuario");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            idUsuario = new Guid("2cc26499-e267-43f9-9a2b-ac8c456020e6"),
                            email = "allan@allan.com",
                            idTipoUsuario = new Guid("f36a1eeb-7da0-4494-8d7f-75ab065b5ef9"),
                            nome = "Allan Rodrigues",
                            senha = "$2a$11$C2RPbDEaAqTlNwdkf/sXqud7UwCVy2pSk/f/O4WHN82SgMJRyH5/W"
                        },
                        new
                        {
                            idUsuario = new Guid("620f8aa7-0f7f-4f2d-85dc-3093e7c18568"),
                            email = "everton@everton.com",
                            idTipoUsuario = new Guid("4833f49b-57d1-4c9e-a06b-6baa7bdc51d4"),
                            nome = "Everton Araujo",
                            senha = "$2a$11$JluE6BFJjlxWmcDZDqfX.O9pbnlVNGttCo77Tolv4fjpVA.bokV9u"
                        });
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.Comentario", b =>
                {
                    b.HasOne("senai_eventPlus_webApi_codeFirst_jwt.Domains.Evento", "evento")
                        .WithMany()
                        .HasForeignKey("idEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("senai_eventPlus_webApi_codeFirst_jwt.Domains.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("evento");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.Evento", b =>
                {
                    b.HasOne("senai_eventPlus_webApi_codeFirst_jwt.Domains.Instituicao", "instituicao")
                        .WithMany()
                        .HasForeignKey("idInstituicao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("senai_eventPlus_webApi_codeFirst_jwt.Domains.TiposEvento", "tipoEvento")
                        .WithMany()
                        .HasForeignKey("idTipoEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("instituicao");

                    b.Navigation("tipoEvento");
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.PresencasEvento", b =>
                {
                    b.HasOne("senai_eventPlus_webApi_codeFirst_jwt.Domains.Evento", "evento")
                        .WithMany()
                        .HasForeignKey("idEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("senai_eventPlus_webApi_codeFirst_jwt.Domains.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("evento");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.Usuario", b =>
                {
                    b.HasOne("senai_eventPlus_webApi_codeFirst_jwt.Domains.TiposUsuario", "tiposUsuario")
                        .WithMany()
                        .HasForeignKey("idTipoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tiposUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
