// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using senai_eventPlus_webApi_codeFirst_jwt.Contexts;

#nullable disable

namespace senai_eventPlus_webApi_codeFirst_jwt.Migrations
{
    [DbContext(typeof(EventPlusContext))]
    partial class EventPlusContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.Comentario", b =>
                {
                    b.Property<Guid>("idComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("exibe")
                        .HasColumnType("BIT");

                    b.Property<Guid>("idEvento")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("idComentario");

                    b.HasIndex("idEvento");

                    b.HasIndex("idUsuario");

                    b.ToTable("Comentario");

                    b.HasData(
                        new
                        {
                            idComentario = new Guid("8de11d50-499a-4e13-80e4-2b3dc7b56fc6"),
                            descricao = "Excelente evento",
                            exibe = true,
                            idEvento = new Guid("a7adc136-2755-42c4-84a0-6a9a26138684"),
                            idUsuario = new Guid("80648e63-32b2-4c81-9ee6-ba2c4a81b21b")
                        });
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.Evento", b =>
                {
                    b.Property<Guid>("idEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("dataEvento")
                        .HasColumnType("DATE");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("horarioEvento")
                        .HasColumnType("TIME");

                    b.Property<Guid>("idInstituicao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idTipoEvento")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nomeEvento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)");

                    b.HasKey("idEvento");

                    b.HasIndex("idInstituicao");

                    b.HasIndex("idTipoEvento");

                    b.ToTable("Evento");

                    b.HasData(
                        new
                        {
                            idEvento = new Guid("a7adc136-2755-42c4-84a0-6a9a26138684"),
                            dataEvento = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            descricao = "Conceitos básicos do SQL Server, como DDL, DML, DQL.",
                            horarioEvento = new TimeSpan(0, 13, 0, 0, 0),
                            idInstituicao = new Guid("53383ca1-802c-4a22-b7e4-c5c2ffd75fe1"),
                            idTipoEvento = new Guid("2bba658f-96b9-4f6c-bdb9-29367200e03f"),
                            nomeEvento = "Introdução ao banco de dados SQL Server"
                        });
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.Instituicao", b =>
                {
                    b.Property<Guid>("idInstituicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("VARCHAR(14)");

                    b.Property<string>("endereco")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)");

                    b.Property<string>("nomeFantasia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)");

                    b.Property<string>("razaoSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)");

                    b.HasKey("idInstituicao");

                    b.HasIndex("cnpj")
                        .IsUnique();

                    b.ToTable("Instituicao");

                    b.HasData(
                        new
                        {
                            idInstituicao = new Guid("53383ca1-802c-4a22-b7e4-c5c2ffd75fe1"),
                            cnpj = "1234567891012",
                            endereco = "Rua Niteroi 180",
                            nomeFantasia = "DevSchool",
                            razaoSocial = "Escola Internacional de Desenvolvimento"
                        });
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.PresencasEvento", b =>
                {
                    b.Property<Guid>("idPresencasEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idEvento")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("situacao")
                        .HasColumnType("BIT");

                    b.HasKey("idPresencasEvento");

                    b.HasIndex("idEvento");

                    b.HasIndex("idUsuario");

                    b.ToTable("PresencasEvento");

                    b.HasData(
                        new
                        {
                            idPresencasEvento = new Guid("3b749fce-add9-4b64-a5ed-522543cf8b87"),
                            idEvento = new Guid("a7adc136-2755-42c4-84a0-6a9a26138684"),
                            idUsuario = new Guid("80648e63-32b2-4c81-9ee6-ba2c4a81b21b"),
                            situacao = true
                        });
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.TiposEvento", b =>
                {
                    b.Property<Guid>("idTiposEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tipoEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("idTiposEvento");

                    b.HasIndex("tipoEvento")
                        .IsUnique();

                    b.ToTable("TiposEvento");

                    b.HasData(
                        new
                        {
                            idTiposEvento = new Guid("2bba658f-96b9-4f6c-bdb9-29367200e03f"),
                            tipoEvento = "SQL Server"
                        },
                        new
                        {
                            idTiposEvento = new Guid("fb3aa9e5-f1bc-46e8-8607-98856997aba0"),
                            tipoEvento = "C#"
                        });
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.TiposUsuario", b =>
                {
                    b.Property<Guid>("idTipoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tipoUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("idTipoUsuario");

                    b.HasIndex("tipoUsuario")
                        .IsUnique();

                    b.ToTable("TipoUsuario");

                    b.HasData(
                        new
                        {
                            idTipoUsuario = new Guid("50b39a82-c131-453a-b459-b6ff83f9b56f"),
                            tipoUsuario = "Administrador"
                        },
                        new
                        {
                            idTipoUsuario = new Guid("135ceb75-41a8-4231-8c2b-39c03e3eda87"),
                            tipoUsuario = "Comum"
                        });
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.Usuario", b =>
                {
                    b.Property<Guid>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)");

                    b.Property<Guid>("idTipoUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("idUsuario");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("idTipoUsuario");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            idUsuario = new Guid("7e0ad881-69ad-4a96-85ee-dd5772505022"),
                            email = "allan@allan.com",
                            idTipoUsuario = new Guid("50b39a82-c131-453a-b459-b6ff83f9b56f"),
                            nome = "Allan Rodrigues",
                            senha = "$2a$11$MRHQETBDTEjYKcGhZ/9vCeT82mdyeRZH/dBNHVJjGnMUTSMteI0t6"
                        },
                        new
                        {
                            idUsuario = new Guid("80648e63-32b2-4c81-9ee6-ba2c4a81b21b"),
                            email = "everton@everton.com",
                            idTipoUsuario = new Guid("135ceb75-41a8-4231-8c2b-39c03e3eda87"),
                            nome = "Everton Araujo",
                            senha = "$2a$11$N/Up7CExckF5DGmJ9ZfXjOm454IRoyYr39jVBwp36UBA4OQBvyadW"
                        });
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.Comentario", b =>
                {
                    b.HasOne("senai_eventPlus_webApi_codeFirst_jwt.Domains.Evento", "evento")
                        .WithMany()
                        .HasForeignKey("idEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("senai_eventPlus_webApi_codeFirst_jwt.Domains.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("evento");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.Evento", b =>
                {
                    b.HasOne("senai_eventPlus_webApi_codeFirst_jwt.Domains.Instituicao", "instituicao")
                        .WithMany()
                        .HasForeignKey("idInstituicao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("senai_eventPlus_webApi_codeFirst_jwt.Domains.TiposEvento", "tipoEvento")
                        .WithMany()
                        .HasForeignKey("idTipoEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("instituicao");

                    b.Navigation("tipoEvento");
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.PresencasEvento", b =>
                {
                    b.HasOne("senai_eventPlus_webApi_codeFirst_jwt.Domains.Evento", "evento")
                        .WithMany()
                        .HasForeignKey("idEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("senai_eventPlus_webApi_codeFirst_jwt.Domains.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("evento");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.Usuario", b =>
                {
                    b.HasOne("senai_eventPlus_webApi_codeFirst_jwt.Domains.TiposUsuario", "tiposUsuario")
                        .WithMany()
                        .HasForeignKey("idTipoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tiposUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
